import type { EmulatorConfig } from './emulator-config'

export default [
  {
    name: 'Huawei_Phone',
    deviceType: 'phone',
    resolutionWidth: 1260,
    resolutionHeight: 2720,
    physicalWidth: 72,
    physicalHeight: 156,
    diagonalSize: 6.82,
    density: 520,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    api: 12,
  },
  {
    name: 'Huawei_Phone',
    deviceType: 'phone',
    resolutionWidth: 1260,
    resolutionHeight: 2720,
    physicalWidth: 72,
    physicalHeight: 156,
    diagonalSize: 6.82,
    density: 520,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    api: 11,
  },
  {
    name: 'Huawei_Foldable',
    deviceType: 'foldable',
    resolutionWidth: 2224,
    resolutionHeight: 2496,
    physicalWidth: 158,
    physicalHeight: 141,
    density: 500,
    diagonalSize: 7.85,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    coverResolutionWidth: 1080,
    coverResolutionHeight: 2504,
    coverDiagonalSize: 6.4,
    api: 12,
  },
  {
    name: 'Huawei_Tablet',
    deviceType: 'tablet',
    resolutionWidth: 2560,
    resolutionHeight: 1600,
    physicalWidth: 237,
    physicalHeight: 148,
    density: 360,
    diagonalSize: 11,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    api: 12,
  },
  {
    name: 'Huawei_Phone',
    deviceType: 'phone',
    resolutionWidth: 1260,
    resolutionHeight: 2720,
    physicalWidth: 72,
    physicalHeight: 156,
    diagonalSize: 6.82,
    density: 520,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    api: 13,
  },
  {
    name: 'Huawei_Foldable',
    deviceType: 'foldable',
    resolutionWidth: 2224,
    resolutionHeight: 2496,
    physicalWidth: 158,
    physicalHeight: 141,
    density: 500,
    diagonalSize: 7.85,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    coverResolutionWidth: 1080,
    coverResolutionHeight: 2504,
    coverDiagonalSize: 6.4,
    api: 13,
  },
  {
    name: 'Huawei_Tablet',
    deviceType: 'tablet',
    resolutionWidth: 2560,
    resolutionHeight: 1600,
    physicalWidth: 237,
    physicalHeight: 148,
    density: 360,
    diagonalSize: 11,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    api: 13,
  },
  {
    name: 'Huawei_Phone',
    deviceType: 'phone',
    resolutionWidth: 1260,
    resolutionHeight: 2720,
    physicalWidth: 72,
    physicalHeight: 156,
    diagonalSize: 6.82,
    density: 520,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    api: 14,
  },
  {
    name: 'Huawei_Foldable',
    deviceType: 'foldable',
    resolutionWidth: 2224,
    resolutionHeight: 2496,
    physicalWidth: 158,
    physicalHeight: 141,
    density: 500,
    diagonalSize: 7.85,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    coverResolutionWidth: 1080,
    coverResolutionHeight: 2504,
    coverDiagonalSize: 6.4,
    api: 14,
  },
  {
    name: 'Huawei_Tablet',
    deviceType: 'tablet',
    resolutionWidth: 2560,
    resolutionHeight: 1600,
    physicalWidth: 237,
    physicalHeight: 148,
    density: 360,
    diagonalSize: 11,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    api: 14,
  },
  {
    name: 'Huawei_Phone',
    deviceType: 'phone',
    resolutionWidth: 1260,
    resolutionHeight: 2720,
    physicalWidth: 72,
    physicalHeight: 156,
    diagonalSize: 6.82,
    density: 520,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    api: 15,
  },
  {
    name: 'Huawei_Foldable',
    deviceType: 'foldable',
    resolutionWidth: 2224,
    resolutionHeight: 2496,
    physicalWidth: 158,
    physicalHeight: 141,
    density: 500,
    diagonalSize: 7.85,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    coverResolutionWidth: 1080,
    coverResolutionHeight: 2504,
    coverDiagonalSize: 6.4,
    api: 15,
  },
  {
    name: 'Huawei_Tablet',
    deviceType: 'tablet',
    resolutionWidth: 2560,
    resolutionHeight: 1600,
    physicalWidth: 237,
    physicalHeight: 148,
    density: 360,
    diagonalSize: 11,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    api: 15,
  },
  {
    name: 'Huawei_Phone',
    deviceType: 'phone',
    resolutionWidth: 1260,
    resolutionHeight: 2720,
    physicalWidth: 72,
    physicalHeight: 156,
    diagonalSize: 6.82,
    density: 520,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    api: 16,
  },
  {
    name: 'Huawei_Foldable',
    deviceType: 'foldable',
    resolutionWidth: 2224,
    resolutionHeight: 2496,
    physicalWidth: 158,
    physicalHeight: 141,
    density: 500,
    diagonalSize: 7.85,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    coverResolutionWidth: 1080,
    coverResolutionHeight: 2504,
    coverDiagonalSize: 6.4,
    api: 16,
  },
  {
    name: 'Huawei_Tablet',
    deviceType: 'tablet',
    resolutionWidth: 2560,
    resolutionHeight: 1600,
    physicalWidth: 237,
    physicalHeight: 148,
    density: 360,
    diagonalSize: 11,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    api: 16,
  },
  {
    name: 'Huawei_Phone',
    deviceType: 'phone',
    resolutionWidth: 1260,
    resolutionHeight: 2720,
    physicalWidth: 72,
    physicalHeight: 156,
    diagonalSize: 6.82,
    density: 520,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    api: 17,
  },
  {
    name: 'Huawei_2in1',
    deviceType: '2in1',
    resolutionWidth: 2160,
    resolutionHeight: 1440,
    physicalWidth: 65,
    physicalHeight: 141,
    diagonalSize: 14.2,
    density: 200,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    api: 17,
  },
  {
    name: 'Huawei_Foldable',
    deviceType: 'foldable',
    resolutionWidth: 2224,
    resolutionHeight: 2496,
    physicalWidth: 158,
    physicalHeight: 141,
    density: 500,
    diagonalSize: 7.85,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    coverResolutionWidth: 1080,
    coverResolutionHeight: 2504,
    coverDiagonalSize: 6.4,
    api: 17,
  },
  {
    name: 'Huawei_Tablet',
    deviceType: 'tablet',
    resolutionWidth: 2560,
    resolutionHeight: 1600,
    physicalWidth: 237,
    physicalHeight: 148,
    density: 360,
    diagonalSize: 11,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    api: 17,
  },
  {
    name: 'Huawei_WideFold',
    deviceType: 'widefold',
    resolutionWidth: 1320,
    resolutionHeight: 2120,
    physicalWidth: 84,
    physicalHeight: 134,
    density: 480,
    diagonalSize: 6.3,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    coverResolutionWidth: 980,
    coverResolutionHeight: 980,
    coverDiagonalSize: 3.5,
    api: 17,
  },
  {
    name: 'Huawei_Phone_AllinOne',
    deviceType: 'phone_all',
    api: 18,
    children: [
      {
        name: 'Huawei_Phone',
        deviceType: 'phone',
        resolutionWidth: 1260,
        resolutionHeight: 2720,
        physicalWidth: 72,
        physicalHeight: 156,
        diagonalSize: 6.82,
        density: 520,
        memoryRamSize: 4096,
        datadiskSize: 6144,
        procNumber: 4,
        api: 18,
      },
    ],
  },
  {
    name: 'Huawei_Phone_AllinOne',
    deviceType: 'phone_all',
    api: 19,
    children: [
      {
        name: 'Huawei_Phone',
        deviceType: 'phone',
        resolutionWidth: 1260,
        resolutionHeight: 2720,
        physicalWidth: 72,
        physicalHeight: 156,
        diagonalSize: 6.82,
        density: 520,
        memoryRamSize: 4096,
        datadiskSize: 6144,
        procNumber: 4,
        api: 19,
      },
      {
        name: 'Huawei_TripleFold',
        deviceType: 'triplefold',
        resolutionWidth: 3184,
        resolutionHeight: 2232,
        physicalWidth: 219,
        physicalHeight: 156,
        density: 460,
        diagonalSize: 10.2,
        memoryRamSize: 4096,
        datadiskSize: 6144,
        procNumber: 4,
        singleResolutionHeight: 2232,
        singleResolutionWidth: 1008,
        singleDiagonalSize: 6.4,
        doubleResolutionWidth: 2048,
        doubleResolutionHeight: 2232,
        doubleDiagonalSize: 7.9,
        api: 19,
      },
    ],
  },
  {
    name: 'Huawei_TV',
    deviceType: 'tv',
    resolutionWidth: 3840,
    resolutionHeight: 2160,
    physicalWidth: 247,
    physicalHeight: 147,
    density: 480,
    diagonalSize: 98,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    api: 19,
  },
  {
    name: 'Huawei_Phone_AllinOne',
    deviceType: 'phone_all',
    api: 20,
    children: [
      {
        name: 'Huawei_Phone',
        deviceType: 'phone',
        resolutionWidth: 1316,
        resolutionHeight: 2832,
        physicalWidth: 72,
        physicalHeight: 156,
        diagonalSize: 6.9,
        density: 560,
        memoryRamSize: 4096,
        datadiskSize: 6144,
        procNumber: 4,
        api: 20,
      },
      {
        name: 'Huawei_Foldable',
        deviceType: 'foldable',
        resolutionWidth: 2224,
        resolutionHeight: 2496,
        physicalWidth: 158,
        physicalHeight: 141,
        density: 500,
        diagonalSize: 7.85,
        memoryRamSize: 4096,
        datadiskSize: 6144,
        procNumber: 4,
        coverResolutionWidth: 1080,
        coverResolutionHeight: 2504,
        coverDiagonalSize: 6.4,
        api: 20,
      },
      {
        name: 'Huawei_TripleFold',
        deviceType: 'triplefold',
        resolutionWidth: 3184,
        resolutionHeight: 2232,
        physicalWidth: 219,
        physicalHeight: 156,
        density: 460,
        diagonalSize: 10.2,
        memoryRamSize: 4096,
        datadiskSize: 6144,
        procNumber: 4,
        singleResolutionHeight: 2232,
        singleResolutionWidth: 1008,
        singleDiagonalSize: 6.4,
        doubleResolutionWidth: 2048,
        doubleResolutionHeight: 2232,
        doubleDiagonalSize: 7.9,
        api: 20,
      },
      {
        name: 'Huawei_WideFold',
        deviceType: 'widefold',
        resolutionWidth: 1320,
        resolutionHeight: 2120,
        physicalWidth: 84,
        physicalHeight: 134,
        density: 480,
        diagonalSize: 6.3,
        memoryRamSize: 4096,
        datadiskSize: 6144,
        procNumber: 4,
        coverResolutionWidth: 980,
        coverResolutionHeight: 980,
        coverDiagonalSize: 3.5,
        api: 20,
      },
    ],
  },
  {
    name: 'Huawei_PC_AllinOne',
    deviceType: 'pc_all',
    api: 20,
    children: [
      {
        name: 'Huawei_2in1',
        deviceType: '2in1',
        resolutionWidth: 3120,
        resolutionHeight: 2080,
        physicalWidth: 300,
        physicalHeight: 200,
        diagonalSize: 14.2,
        density: 304,
        memoryRamSize: 4096,
        datadiskSize: 6144,
        procNumber: 4,
        api: 20,
      },
      {
        name: 'Huawei_2in1_Foldable',
        deviceType: '2in1_foldable',
        resolutionWidth: 3296,
        resolutionHeight: 2472,
        physicalWidth: 370,
        physicalHeight: 280,
        diagonalSize: 18,
        density: 288,
        memoryRamSize: 4096,
        datadiskSize: 6144,
        procNumber: 4,
        coverResolutionWidth: 2472,
        coverResolutionHeight: 1648,
        coverDiagonalSize: 13,
        api: 20,
      },
    ],
  },
  {
    name: 'Huawei_Tablet',
    deviceType: 'tablet',
    resolutionWidth: 2560,
    resolutionHeight: 1600,
    physicalWidth: 237,
    physicalHeight: 148,
    density: 360,
    diagonalSize: 11,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    api: 20,
  },
  {
    name: 'Huawei_Wearable',
    deviceType: 'wearable',
    resolutionWidth: 466,
    resolutionHeight: 466,
    physicalWidth: 41,
    physicalHeight: 41,
    diagonalSize: 1.6,
    density: 320,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    api: 20,
  },
  {
    name: 'Huawei_Phone_AllinOne',
    deviceType: 'phone_all',
    api: 21,
    children: [
      {
        name: 'Huawei_Phone',
        deviceType: 'phone',
        resolutionWidth: 1316,
        resolutionHeight: 2832,
        physicalWidth: 72,
        physicalHeight: 156,
        diagonalSize: 6.9,
        density: 560,
        memoryRamSize: 4096,
        datadiskSize: 6144,
        procNumber: 4,
        api: 21,
      },
      {
        name: 'Huawei_Foldable',
        deviceType: 'foldable',
        resolutionWidth: 2224,
        resolutionHeight: 2496,
        physicalWidth: 158,
        physicalHeight: 141,
        density: 500,
        diagonalSize: 7.85,
        memoryRamSize: 4096,
        datadiskSize: 6144,
        procNumber: 4,
        coverResolutionWidth: 1080,
        coverResolutionHeight: 2504,
        coverDiagonalSize: 6.4,
        api: 21,
      },
      {
        name: 'Huawei_TripleFold',
        deviceType: 'triplefold',
        resolutionWidth: 3184,
        resolutionHeight: 2232,
        physicalWidth: 219,
        physicalHeight: 156,
        density: 460,
        diagonalSize: 10.2,
        memoryRamSize: 4096,
        datadiskSize: 6144,
        procNumber: 4,
        singleResolutionHeight: 2232,
        singleResolutionWidth: 1008,
        singleDiagonalSize: 6.4,
        doubleResolutionWidth: 2048,
        doubleResolutionHeight: 2232,
        doubleDiagonalSize: 7.9,
        api: 21,
      },
      {
        name: 'Huawei_WideFold',
        deviceType: 'widefold',
        resolutionWidth: 1320,
        resolutionHeight: 2120,
        physicalWidth: 84,
        physicalHeight: 134,
        density: 480,
        diagonalSize: 6.3,
        memoryRamSize: 4096,
        datadiskSize: 6144,
        procNumber: 4,
        coverResolutionWidth: 980,
        coverResolutionHeight: 980,
        coverDiagonalSize: 3.5,
        api: 21,
      },
    ],
  },
  {
    name: 'Huawei_PC_AllinOne',
    deviceType: 'pc_all',
    api: 21,
    children: [
      {
        name: 'Huawei_2in1',
        deviceType: '2in1',
        resolutionWidth: 3120,
        resolutionHeight: 2080,
        physicalWidth: 300,
        physicalHeight: 200,
        diagonalSize: 14.2,
        density: 304,
        memoryRamSize: 4096,
        datadiskSize: 6144,
        procNumber: 4,
        api: 21,
      },
      {
        name: 'Huawei_2in1_Foldable',
        deviceType: '2in1_foldable',
        resolutionWidth: 3296,
        resolutionHeight: 2472,
        physicalWidth: 370,
        physicalHeight: 280,
        diagonalSize: 18,
        density: 288,
        memoryRamSize: 4096,
        datadiskSize: 6144,
        procNumber: 4,
        coverResolutionWidth: 2472,
        coverResolutionHeight: 1648,
        coverDiagonalSize: 13,
        api: 21,
      },
    ],
  },
  {
    name: 'Huawei_Tablet',
    deviceType: 'tablet',
    resolutionWidth: 2560,
    resolutionHeight: 1600,
    physicalWidth: 237,
    physicalHeight: 148,
    density: 360,
    diagonalSize: 11,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    api: 21,
  },
  {
    name: 'Huawei_Wearable',
    deviceType: 'wearable',
    resolutionWidth: 466,
    resolutionHeight: 466,
    physicalWidth: 41,
    physicalHeight: 41,
    diagonalSize: 1.6,
    density: 320,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    api: 21,
  },
  {
    name: 'Huawei_Phone_AllinOne',
    deviceType: 'phone_all',
    api: 22,
    children: [
      {
        name: 'Huawei_Phone',
        deviceType: 'phone',
        resolutionWidth: 1316,
        resolutionHeight: 2832,
        physicalWidth: 72,
        physicalHeight: 156,
        diagonalSize: 6.9,
        density: 560,
        memoryRamSize: 4096,
        datadiskSize: 6144,
        procNumber: 4,
        api: 22,
      },
      {
        name: 'Huawei_Foldable',
        deviceType: 'foldable',
        resolutionWidth: 2224,
        resolutionHeight: 2496,
        physicalWidth: 158,
        physicalHeight: 141,
        density: 500,
        diagonalSize: 7.85,
        memoryRamSize: 4096,
        datadiskSize: 6144,
        procNumber: 4,
        coverResolutionWidth: 1080,
        coverResolutionHeight: 2504,
        coverDiagonalSize: 6.4,
        api: 22,
      },
      {
        name: 'Huawei_TripleFold',
        deviceType: 'triplefold',
        resolutionWidth: 3184,
        resolutionHeight: 2232,
        physicalWidth: 219,
        physicalHeight: 156,
        density: 460,
        diagonalSize: 10.2,
        memoryRamSize: 4096,
        datadiskSize: 6144,
        procNumber: 4,
        singleResolutionHeight: 2232,
        singleResolutionWidth: 1008,
        singleDiagonalSize: 6.4,
        doubleResolutionWidth: 2048,
        doubleResolutionHeight: 2232,
        doubleDiagonalSize: 7.9,
        api: 22,
      },
      {
        name: 'Huawei_WideFold',
        deviceType: 'widefold',
        resolutionWidth: 1320,
        resolutionHeight: 2120,
        physicalWidth: 84,
        physicalHeight: 134,
        density: 480,
        diagonalSize: 6.3,
        memoryRamSize: 4096,
        datadiskSize: 6144,
        procNumber: 4,
        coverResolutionWidth: 980,
        coverResolutionHeight: 980,
        coverDiagonalSize: 3.5,
        api: 22,
      },
    ],
  },
  {
    name: 'Huawei_PC_AllinOne',
    deviceType: 'pc_all',
    api: 22,
    children: [
      {
        name: 'Huawei_2in1',
        deviceType: '2in1',
        resolutionWidth: 3120,
        resolutionHeight: 2080,
        physicalWidth: 300,
        physicalHeight: 200,
        diagonalSize: 14.2,
        density: 304,
        memoryRamSize: 4096,
        datadiskSize: 6144,
        procNumber: 4,
        api: 22,
      },
      {
        name: 'Huawei_2in1_Foldable',
        deviceType: '2in1_foldable',
        resolutionWidth: 3296,
        resolutionHeight: 2472,
        physicalWidth: 370,
        physicalHeight: 280,
        diagonalSize: 18,
        density: 288,
        memoryRamSize: 4096,
        datadiskSize: 6144,
        procNumber: 4,
        coverResolutionWidth: 2472,
        coverResolutionHeight: 1648,
        coverDiagonalSize: 13,
        api: 22,
      },
    ],
  },
  {
    name: 'Huawei_Tablet',
    deviceType: 'tablet',
    resolutionWidth: 2560,
    resolutionHeight: 1600,
    physicalWidth: 237,
    physicalHeight: 148,
    density: 360,
    diagonalSize: 11,
    memoryRamSize: 4096,
    datadiskSize: 6144,
    procNumber: 4,
    api: 22,
  },
] satisfies EmulatorConfig as EmulatorConfig
